project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "site-url: "https://viktoriaaxelsson.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false
    items:
      - text: "Mini-Project 1"
        href: "mp01.qmd"
      - text: "Mini-Project 3"
        href: "mp03.qmd"

format:
  html:
    theme: <THEME>
    toc: false

editor:
  mode: source